export const GET_OWN_AGENCY_REQUEST = "GET_OWN_AGENCY_REQUEST";
export const GET_OWN_AGENCY_SUCCESS = "GET_OWN_AGENCY_SUCCESS";
export const GET_OWN_AGENCY_FAILURE = "GET_OWN_AGENCY_FAILURE";

export const GET_AGENCY_EMPLOYEES_REQUEST = "GET_AGENCY_EMPLOYEES_REQUEST";
export const GET_AGENCY_EMPLOYEES_SUCCESS = "GET_AGENCY_EMPLOYEES_SUCCESS";
export const GET_AGENCY_EMPLOYEES_FAILURE = "GET_AGENCY_EMPLOYEES_FAILURE";
